//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowLevelHooks.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LowLevelHooks.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Keys.
        /// </summary>
        internal static string CaptureKeysString {
            get {
                return ResourceManager.GetString("CaptureKeysString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mouse.
        /// </summary>
        internal static string CaptureMouseString {
            get {
                return ResourceManager.GetString("CaptureMouseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file..
        /// </summary>
        internal static string NoFileString {
            get {
                return ResourceManager.GetString("NoFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Capturing Keys.
        /// </summary>
        internal static string StopCapturingKeysString {
            get {
                return ResourceManager.GetString("StopCapturingKeysString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Capturing Mouse.
        /// </summary>
        internal static string StopCapturingMouseString {
            get {
                return ResourceManager.GetString("StopCapturingMouseString", resourceCulture);
            }
        }
    }
}
